export enum ServiceUrl {
    UserLogin = "/api/v1/users/signin",
    Dashboard = "/home",
    AddUser = "/api/v1/users/signup",
    AddEvent = "api/v1/users/signin",
    GetEvents = "../../assets/stubs/events.json",
    GetNotifications = "../../assets/stubs/notifications.json",
    GetChallenges = "../../assets/stubs/challenges.json",
    GetPopups = "../../assets/stubs/popups.json",
    GetCoupons = "../../assets/stubs/coupons.json",
    GetRoles = "../../assets/stubs/roles.json",
    GetPrivileges = "../../assets/stubs/privileges.json",
    GetUsers = "../../assets/stubs/users.json",
    GetCategories = "../../assets/stubs/categories.json",
    GetVendors = "../../assets/stubs/vendors.json",
    GetBranches = "../../assets/stubs/branches.json",
    GetPlans = "../../assets/stubs/plans.json",
    GetTransactions = "../../assets/stubs/transactions.json",
    GetUserSteps = "../../assets/stubs/usersteps.json",
    GetUserStepbucks = "../../assets/stubs/userstepbucks.json",
    GetUserGroups = "../../assets/stubs/usergroups.json",
    GetRolePrivileges = "../../assets/stubs/role-privilege.json",
    GetOtherUsers = "../../assets/stubs/otherusers.json"
}