export enum Routes {
    DASHBOARD = '',
    LOGIN = 'login',
    HOME = 'home',
    PRIVILEGES = 'privileges',
    ADDPRIVILEGES = 'addPrivileges',
    EDITPRIVILEGES = 'editPrivileges',
    ROLES = 'roles',
    ADDROLE = 'addRole',
    EDITROLE = 'editRole',
    USERS = 'users',
    ADDUSER = 'addUser',
    EDITUSER = 'editUser',
    VENDORS = 'vendors',
    ADDVENDOR = 'addVendor',
    EDITVENDOR = 'editVendor',
    SUBSCRIPTIONS = 'subscriptions',
    ADDSUBSCRIPTION = 'addSubscription',
    EDITSUBSCRIPTION = 'editSubscription',
}